CREATE TABLE IF NOT EXISTS ´pessoa´(
´Id´ BIGINT(20) NOT NULL AUTO_INCREMENT,
´primeiroNome´ VARCHAR(100) NOT NULL,
´ultimoNome´ VARCHAR(100) NOT NULL,
´Endereco´ VARCHAR(100) NOT NULL,
´Genero´ VARCHAR(20) NOT NULL,
PRIMARY KEY (´id´)
